/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frm;

import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author Mia Pecelj
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        super();
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    

    public JMenu getMenuCategory() {
        return MenuCategory;
    }

    public void setMenuCategory(JMenu MenuCategory) {
        this.MenuCategory = MenuCategory;
    }

    public JMenu getMenuExpense() {
        return MenuExpense;
    }

    public void setMenuExpense(JMenu MenuExpense) {
        this.MenuExpense = MenuExpense;
    }

    public JMenuItem getMenuItemAddCategory() {
        return MenuItemAddCategory;
    }

    public void setMenuItemAddCategory(JMenuItem MenuItemAddCategory) {
        this.MenuItemAddCategory = MenuItemAddCategory;
    }

    public JMenuItem getMenuItemAddExpense() {
        return MenuItemAddExpense;
    }

    public void setMenuItemAddExpense(JMenuItem MenuItemAddExpense) {
        this.MenuItemAddExpense = MenuItemAddExpense;
    }

    public JMenuItem getMenuItemCreateMB() {
        return MenuItemCreateMB;
    }

    public void setMenuItemCreateMB(JMenuItem MenuItemCreateMB) {
        this.MenuItemCreateMB = MenuItemCreateMB;
    }

    

    public JMenuItem getMenuItemShowExepenses() {
        return MenuItemShowExepenses;
    }

    public void setMenuItemShowExepenses(JMenuItem MenuItemShowExepenses) {
        this.MenuItemShowExepenses = MenuItemShowExepenses;
    }

    public JMenuItem getMenuItemViewMB() {
        return MenuItemViewMB;
    }

    public void setMenuItemViewMB(JMenuItem MenuItemViewMB) {
        this.MenuItemViewMB = MenuItemViewMB;
    }

    public JMenu getMenuMonthlyBudget() {
        return MenuMonthlyBudget;
    }

    public void setMenuMonthlyBudget(JMenu MenuMonthlyBudget) {
        this.MenuMonthlyBudget = MenuMonthlyBudget;
    }

    public JMenuBar getjMenuBar1() {
        return jMenuBar1;
    }

    public void setjMenuBar1(JMenuBar jMenuBar1) {
        this.jMenuBar1 = jMenuBar1;
    }

    public JMenuItem getjMenuItem1() {
        return jMenuItem1;
    }

    public void setjMenuItem1(JMenuItem jMenuItem1) {
        this.jMenuItem1 = jMenuItem1;
    }

    public JLabel getLblCurrentUser() {
        return lblCurrentUser;
    }

    public void setLblCurrentUser(JLabel lblCurrentUser) {
        this.lblCurrentUser = lblCurrentUser;
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        lblCurrentUser = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuExpense = new javax.swing.JMenu();
        MenuItemAddExpense = new javax.swing.JMenuItem();
        MenuItemShowExepenses = new javax.swing.JMenuItem();
        MenuCategory = new javax.swing.JMenu();
        MenuItemAddCategory = new javax.swing.JMenuItem();
        MenuMonthlyBudget = new javax.swing.JMenu();
        MenuItemCreateMB = new javax.swing.JMenuItem();
        MenuItemViewMB = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnLogOut.setText("Log out");

        MenuExpense.setText("Expense");

        MenuItemAddExpense.setText("Add Expense");
        MenuItemAddExpense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAddExpenseActionPerformed(evt);
            }
        });
        MenuExpense.add(MenuItemAddExpense);

        MenuItemShowExepenses.setText("Show all");
        MenuItemShowExepenses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemShowExepensesActionPerformed(evt);
            }
        });
        MenuExpense.add(MenuItemShowExepenses);

        jMenuBar1.add(MenuExpense);

        MenuCategory.setText("Category");

        MenuItemAddCategory.setText("Add");
        MenuItemAddCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAddCategoryActionPerformed(evt);
            }
        });
        MenuCategory.add(MenuItemAddCategory);

        jMenuBar1.add(MenuCategory);

        MenuMonthlyBudget.setText("MonthlyBudget");

        MenuItemCreateMB.setText("Create");
        MenuItemCreateMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCreateMBActionPerformed(evt);
            }
        });
        MenuMonthlyBudget.add(MenuItemCreateMB);

        MenuItemViewMB.setText("View");
        MenuItemViewMB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemViewMBActionPerformed(evt);
            }
        });
        MenuMonthlyBudget.add(MenuItemViewMB);

        jMenuBar1.add(MenuMonthlyBudget);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCurrentUser)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(522, Short.MAX_VALUE)
                .addComponent(btnLogOut)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblCurrentUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 408, Short.MAX_VALUE)
                .addComponent(btnLogOut)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemAddCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAddCategoryActionPerformed

    }//GEN-LAST:event_MenuItemAddCategoryActionPerformed

    private void MenuItemAddExpenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAddExpenseActionPerformed

    }//GEN-LAST:event_MenuItemAddExpenseActionPerformed

    private void MenuItemCreateMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCreateMBActionPerformed
    }//GEN-LAST:event_MenuItemCreateMBActionPerformed

    private void MenuItemViewMBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemViewMBActionPerformed
    }//GEN-LAST:event_MenuItemViewMBActionPerformed

    private void MenuItemShowExepensesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemShowExepensesActionPerformed
    }//GEN-LAST:event_MenuItemShowExepensesActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuCategory;
    private javax.swing.JMenu MenuExpense;
    private javax.swing.JMenuItem MenuItemAddCategory;
    private javax.swing.JMenuItem MenuItemAddExpense;
    private javax.swing.JMenuItem MenuItemCreateMB;
    private javax.swing.JMenuItem MenuItemShowExepenses;
    private javax.swing.JMenuItem MenuItemViewMB;
    private javax.swing.JMenu MenuMonthlyBudget;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblCurrentUser;
    // End of variables declaration//GEN-END:variables

    

    public void getJmiCategoryAddActionListener(ActionListener actionListener) {
        MenuItemAddCategory.addActionListener(actionListener);
    }

    public void getJmiMonthlyBudgetAddActionListener(ActionListener actionListener) {
        MenuItemCreateMB.addActionListener(actionListener);
    }

    public void getJmiMonthlyBudgetViewAddActionListener(ActionListener actionListener) {
        MenuItemViewMB.addActionListener(actionListener);
       }

    public void getJmiExpenseAddActionListener(ActionListener actionListener) {
        MenuItemAddExpense.addActionListener(actionListener);
    }

    public void getJmiExpenseViewActionListener(ActionListener actionListener) {
        MenuItemShowExepenses.addActionListener(actionListener);
    }

    public void getLogOut(ActionListener actionListener) {
        btnLogOut.addActionListener(actionListener);
    }

  

}
