/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frm;


import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Mia Pecelj
 */
public class FrmMonthlyBudget extends javax.swing.JDialog {


    /**
     * Creates new form FrmMonthlyBudget
     */
    public FrmMonthlyBudget(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }

    public JTable getTblBudgetItems() {
        return tblBudgetItems;
    }

    public void setTblBudgetItems(JTable tblBudgetItems) {
        this.tblBudgetItems = tblBudgetItems;
    }

    public JTextField getLimit() {
        return Limit;
    }

    public void setLimit(JTextField Limit) {
        this.Limit = Limit;
    }

    public JButton getBtnBudgetItem() {
        return btnBudgetItem;
    }

    public void setBtnBudgetItem(JButton btnBudgetItem) {
        this.btnBudgetItem = btnBudgetItem;
    }

    public JButton getBtnCancel() {
        return btnCancel;
    }

    public void setBtnCancel(JButton btnCancel) {
        this.btnCancel = btnCancel;
    }

    public JButton getBtnSave() {
        return btnSave;
    }

    public void setBtnSave(JButton btnSave) {
        this.btnSave = btnSave;
    }

    public JComboBox getCbMonth() {
        return cbMonth;
    }

    public void setCbMonth(JComboBox cbMonth) {
        this.cbMonth = cbMonth;
    }

    public JComboBox getCbYear() {
        return cbYear;
    }

    public void setCbYear(JComboBox cbYear) {
        this.cbYear = cbYear;
    }

    public JLabel getLblErrorLimit() {
        return lblErrorLimit;
    }

    public void setLblErrorLimit(JLabel lblErrorLimit) {
        this.lblErrorLimit = lblErrorLimit;
    }

    public JLabel getLblInputMonth() {
        return lblInputMonth;
    }

    public void setLblInputMonth(JLabel lblInputMonth) {
        this.lblInputMonth = lblInputMonth;
    }

    public JLabel getLblInputYear() {
        return lblInputYear;
    }

    public void setLblInputYear(JLabel lblInputYear) {
        this.lblInputYear = lblInputYear;
    }

    public JLabel getLblLimit() {
        return lblLimit;
    }

    public void setLblLimit(JLabel lblLimit) {
        this.lblLimit = lblLimit;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLimit = new javax.swing.JLabel();
        Limit = new javax.swing.JTextField();
        lblErrorLimit = new javax.swing.JLabel();
        lblInputMonth = new javax.swing.JLabel();
        cbMonth = new javax.swing.JComboBox();
        lblInputYear = new javax.swing.JLabel();
        cbYear = new javax.swing.JComboBox();
        btnBudgetItem = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBudgetItems = new javax.swing.JTable();
        btnRemove = new javax.swing.JButton();
        btnAddCategory = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblLimit.setText("Limit:");

        lblErrorLimit.setForeground(new java.awt.Color(255, 0, 0));

        lblInputMonth.setText("Month:");

        lblInputYear.setText("Year:");

        btnBudgetItem.setText("Add budget item");
        btnBudgetItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBudgetItemActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        tblBudgetItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Limit"
            }
        ));
        jScrollPane1.setViewportView(tblBudgetItems);

        btnRemove.setText("Remove");

        btnAddCategory.setText("Add category");
        btnAddCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCategoryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLimit)
                                .addGap(18, 18, 18)
                                .addComponent(Limit, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblErrorLimit))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnCancel)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblInputMonth)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(lblInputYear)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(48, 48, 48)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSave))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGap(144, 144, 144)
                                .addComponent(btnRemove))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnAddCategory, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBudgetItem, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLimit)
                    .addComponent(Limit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorLimit)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInputMonth)
                    .addComponent(cbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInputYear)
                    .addComponent(cbYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnAddCategory)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBudgetItem)
                    .addComponent(btnRemove))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBudgetItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBudgetItemActionPerformed
        
    }//GEN-LAST:event_btnBudgetItemActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddCategoryActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Limit;
    private javax.swing.JButton btnAddCategory;
    private javax.swing.JButton btnBudgetItem;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cbMonth;
    private javax.swing.JComboBox cbYear;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblErrorLimit;
    private javax.swing.JLabel lblInputMonth;
    private javax.swing.JLabel lblInputYear;
    private javax.swing.JLabel lblLimit;
    private javax.swing.JTable tblBudgetItems;
    // End of variables declaration//GEN-END:variables

    public void getJmiBudgetItemActionListener(ActionListener actionListener) {
        btnBudgetItem.addActionListener(actionListener);
    }

    public void getCancelActionListener(ActionListener actionListener) {
        btnCancel.addActionListener(actionListener);
    }

    public void getSaveActionListener(ActionListener actionListener) {
        btnSave.addActionListener(actionListener);
    }

    public void addBtnRemoveItemActionListener(ActionListener actionListener) {
        btnRemove.addActionListener(actionListener);
    }

    public void addBtnCategoryItemActionListener(ActionListener actionListener) {
        btnAddCategory.addActionListener(actionListener);
    }

   
}
